### PR TITLE
location = MAN and strawman for annotator agreement notebook

### PR DESCRIPTION
**Pull request by royatxdotai**

### CODE REVIEW

**Comment by royatxdotai** [comment]
@debajyotidatta i added some if-s to prevent `KeyError`, will test some more tomorrow.

**Comment by royatxdotai** [comment]
verified that the notebook runs for 1 day: https://github.com/xdotai/metrics-mcmetricsface/blob/roy_remove_NYC_trainer/nbs/AITProductivity.ipynb

**Comment by royatxdotai** [comment]
https://xdotai.slack.com/files/roy/F4WU1NVRC/pasted_image_at_2017_04_07_01_16_pm.png

**Comment by debajyotidatta** [comment]
LGTM!

**Pull request merged**
